import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { QueryClient, QueryClientProvider, useQuery } from '@tanstack/react-query';
import { BrowserRouter, NavLink, Route, Routes, useNavigate } from 'react-router-dom';
import { create } from 'zustand';
import './styles.css';

const API = import.meta.env.VITE_API_URL || 'http://localhost:8000/api/v1';
type Store = { token: string; setToken: (v: string) => void };
const useAuth = create<Store>((set) => ({ token: localStorage.getItem('token') || '', setToken: (token) => { localStorage.setItem('token', token); set({ token }); } }));
async function api(path: string, init: RequestInit = {}) { const token = useAuth.getState().token; const r = await fetch(`${API}${path}`, { ...init, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}`, 'X-Correlation-ID': crypto.randomUUID(), ...(init.headers || {}) } }); if (!r.ok) { if(r.status===401 && path!=='/auth/login'){localStorage.removeItem('token');location.reload();} throw new Error((await r.json()).detail || r.statusText); } return r.json(); }
const fmt = (v: unknown) => v == null || v === '' ? 'Unavailable' : String(v);

function Login() { const setToken = useAuth(s => s.setToken), nav = useNavigate(); const [error, setError] = useState(''); async function submit(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); try { const x = await api('/auth/login', { method: 'POST', body: JSON.stringify({ username: f.get('username'), password: f.get('password') }) }); setToken(x.access_token); nav('/'); } catch (e) { setError(String(e)); } } return <main className="login"><form onSubmit={submit}><span className="eyebrow">LOCAL RESEARCH TERMINAL</span><h1>Market AI</h1><p>Decision support and paper trading for Indian cash equities.</p><label>Username<input name="username" defaultValue="demo" /></label><label>Password<input name="password" type="password" defaultValue="papertrade" /></label><button>Enter paper terminal</button>{error && <p className="error">{error}</p>}<small>No live execution. Every actionable order requires approval.</small></form></main> }
function Layout() { const token = useAuth(s => s.token); if (!token) return <Login/>; const links = [['/','Command Center'],['/scanner','Market Scanner'],['/decisions','Decision Desk'],['/orders','Paper Orders'],['/portfolio','Portfolio'],['/operations','Operations']]; return <div className="shell"><aside><div className="brand">M<span>AI</span></div><div className="badge">DEMO MODE</div><nav>{links.map(([to,label])=><NavLink key={to} to={to} end>{label}</NavLink>)}</nav><div className="safe">● PAPER ONLY<br/><small>Live trading disabled</small></div></aside><section className="content"><header><div><b>NSE Research Workspace</b><small>{new Date().toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST</small></div><span className="feed">● Simulated feed connected</span></header><Routes><Route path="/" element={<Command/>}/><Route path="/scanner" element={<Scanner/>}/><Route path="/decisions" element={<Decisions/>}/><Route path="/orders" element={<Orders/>}/><Route path="/portfolio" element={<Portfolio/>}/><Route path="/operations" element={<Operations/>}/></Routes></section></div> }
function Command(){ const q=useQuery({queryKey:['portfolio'],queryFn:()=>api('/paper/portfolio')}); const s=useQuery({queryKey:['status'],queryFn:()=>api('/system/status')}); const p=q.data||{}; return <Page title="Command Center" sub="Safety, capital and market state at a glance"><div className="notice">Research and simulated execution only. This system does not promise returns.</div><div className="cards"><Card label="Portfolio value" value={`₹${fmt(p.portfolio_value)}`}/><Card label="Available cash" value={`₹${fmt(p.cash)}`}/><Card label="Open positions" value={p.positions?.length ?? '—'}/><Card label="Realised / Unrealised" value={`₹${fmt(p.realised_pnl)} / ₹${fmt(p.unrealised_pnl)}`}/></div><div className="grid2"><Panel title="System guardrails"><Rows values={{'Trading mode':'PAPER','Live execution':'Disabled','Global kill switch':s.data?.kill_switch?'ACTIVE':'Ready','Database':'PostgreSQL source of truth','Reconciliation':p.reconciliation_status,'Last snapshot':p.last_snapshot_at}}/></Panel><Panel title="Risk envelope"><Rows values={{'Risk / trade':'0.5%','Capital / trade':'10%','Daily loss limit':'2%','Max positions':'5','Sector exposure':'25%'}}/></Panel></div></Page>}
function Scanner(){const q=useQuery({queryKey:['scan'],queryFn:()=>api('/scanner/results')});return <Page title="Market Scanner" sub="Versioned evidence across the seeded NSE universe"><Table rows={q.data||[]} cols={['symbol','price','change','relative_volume','regime','data_quality','decision','confidence','strategy','risk_reward']}/></Page>}
function Decisions(){const [symbol,setSymbol]=useState('RELIANCE');const [latest,setLatest]=useState<any>();const q=useQuery({queryKey:['decisions',latest],queryFn:()=>api('/decisions')});async function generate(){setLatest(await api('/decisions/generate',{method:'POST',body:JSON.stringify({instrument_id:symbol})}));}async function approve(id:string){await api(`/approvals/${id}/approve`,{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()}});setLatest({...latest,approved:true});}const rows=latest?[latest,...(q.data||[]).filter((x:any)=>x.id!==latest.id)]:q.data||[];return <Page title="Decision Desk" sub="Evidence first. Approval is a separate human action."><div className="toolbar"><select value={symbol} onChange={e=>setSymbol(e.target.value)}>{['RELIANCE','HDFCBANK','INFY','TCS','SBIN'].map(x=><option>{x}</option>)}</select><button onClick={generate}>Generate decision</button></div>{rows.map((d:any)=><article className="decision" key={d.id}><div><span className={`pill ${d.action}`}>{d.action}</span><h2>{d.symbol}</h2><small>{d.strategy_version}</small></div><div className="tradegrid"><Rows values={{'Entry':d.entry_zone,'Stop loss':d.stop_loss,'Target':d.target,'Risk / reward':d.risk_reward,'Position size':d.position_size,'Monetary risk':d.monetary_risk}}/></div><div><b>Reason codes</b><p>{d.reason_codes?.join(' · ')}</p>{d.approval_id&&!d.approved&&<button onClick={()=>approve(d.approval_id)}>Approve paper order</button>}{d.approved&&<span className="success">Filled in paper account</span>}</div></article>)}</Page>}
function Orders(){const q=useQuery({queryKey:['orders'],queryFn:()=>api('/paper/orders')});return <Page title="Paper Orders" sub="Immutable lifecycle events and simulated fills"><Table rows={q.data||[]} cols={['symbol','side','quantity','filled_quantity','average_price','charges','status','created_at']}/></Page>}
function Portfolio(){const q=useQuery({queryKey:['port'],queryFn:()=>api('/paper/portfolio')});const ledger=useQuery({queryKey:['ledger'],queryFn:()=>api('/paper/cash-ledger')});async function exit(id:string){if(!confirm('Exit this paper position at the simulated market price?'))return;await api(`/paper/positions/${id}/exit`,{method:'POST',body:JSON.stringify({reason:'manual'})});await q.refetch();await ledger.refetch();}return <Page title="Portfolio" sub="PostgreSQL-backed balances and append-only ledger"><div className="cards"><Card label="Cash" value={`₹${fmt(q.data?.cash)}`}/><Card label="Market value" value={`₹${fmt(q.data?.market_value)}`}/><Card label="Realised P&L" value={`₹${fmt(q.data?.realised_pnl)}`}/><Card label="Reconciliation" value={fmt(q.data?.reconciliation_status)}/></div><Panel title="Positions"><div className="tablewrap"><table><thead><tr>{['Symbol','Quantity','Average price','Current price','Charges','Action'].map(x=><th>{x}</th>)}</tr></thead><tbody>{(q.data?.positions||[]).map((p:any)=><tr key={p.id}><td>{p.symbol}</td><td>{p.quantity}</td><td>{p.average_price}</td><td>{p.current_price}</td><td>{p.charges}</td><td><button onClick={()=>exit(p.id)}>Exit</button></td></tr>)}</tbody></table></div></Panel><Panel title="Cash ledger"><Table rows={ledger.data||[]} cols={['created_at','entry_type','amount','source_type','source_id']}/></Panel></Page>}
function Operations(){const q=useQuery({queryKey:['audit'],queryFn:()=>api('/audit')});return <Page title="Operations" sub="Append-only audit evidence"><Table rows={q.data||[]} cols={['timestamp','kind','entity_id']}/></Page>}
function Page({title,sub,children}:{title:string,sub:string,children:React.ReactNode}){return <main><div className="title"><h1>{title}</h1><p>{sub}</p></div>{children}</main>} function Card({label,value}:{label:string,value:unknown}){return <div className="card"><small>{label}</small><strong>{String(value)}</strong></div>} function Panel({title,children}:{title:string,children:React.ReactNode}){return <section className="panel"><h3>{title}</h3>{children}</section>} function Rows({values}:{values:Record<string,unknown>}){return <dl>{Object.entries(values).map(([k,v])=><React.Fragment key={k}><dt>{k}</dt><dd>{fmt(v)}</dd></React.Fragment>)}</dl>} function Table({rows,cols}:{rows:any[],cols:string[]}){return <div className="tablewrap"><table><thead><tr>{cols.map(c=><th>{c.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={r.id||i}>{cols.map(c=><td>{fmt(r[c])}</td>)}</tr>):<tr><td colSpan={cols.length}>No records yet</td></tr>}</tbody></table></div>}
createRoot(document.getElementById('root')!).render(<QueryClientProvider client={new QueryClient()}><BrowserRouter><Layout/></BrowserRouter></QueryClientProvider>);
